### ISSUE TITLE
Action responses

### ISSUE THREAD

**Issue by casualcodex** [ipoddubny/ya-node-asterisk#10]
Hi , 

how can I get action response detail? Like , when I send origination "Action" , I only see 3 lines of response. 
response to action: {
  response: 'Error',
  actionid: '72849233',
  message: 'Originate failed'
}

is it possible to see more of the action response?

ActionID
Response
Failure
Success
Channel
Context
Exten
Application
Data
Reason
Uniqueid
CallerIDNum
CallerIDName

**Comment by ipoddubny** [comment]
With "Async: false" (by default) Asterisk doesn't return any of that.
With "Async: true" Asterisk sends an OriginateResponse event that contains these fields.
Override ActionID in the request and set up an event handler to catch the response:
```js
const actionid = (new Date()).getTime() +'_'+ (Math.random()*1e6^0);
ami.send{
  actionid,
  action: 'Originate',
  'async': 'true',
  /* ... */
});
ami.on('OriginateResponse', res => {
  if (res.actionid === actionid) {
    // this is the response
  }
});
```
(this is a simplified example, doesn't remove the event handler once the event has been received,  and doesn't handle timeouts).
